### ISSUE TITLE
Can't pass level 13 <stash>

### ISSUE THREAD

**Issue by freedomlang** [Gazler/githug#211]
I have did `git stash`, but it can not clean the working directory.

BTW: my git version is 2.8.1, and i have test `git stash` on other repos, it works fine.

**Comment by Gazler** [comment]
Thanks for the report. I can't replicate this. Could you please provide a log of your terminal output when running `git stash`?

**Comment by freedomlang** [comment]
@Gazler 

After i excuted `git stash`, it's output was normal!
```
git stash
#------------
Saved working directory and index state WIP on master: 0206059 Add some lyrics
HEAD is now at 0206059 Add some lyrics
#--------------
git status
#--------------
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   lyrics.txt

no changes added to commit (use "git add" and/or "git commit -a")
#-------------------
git log
#------------------
commit 02060592b31c9e12ffe1b282addf9537c5ef8e1f
Author: Anton Vasin <magnumsmail@gmail.com>
Date:   Mon Dec 3 11:13:07 2012 +0400
```
it's too weird

**Comment by zjuchenyuan** [comment]
I found this issue too, I fixed this problem by using `git init` before `git stash`

**Comment by freedomlang** [comment]
@zjuchenyuan ,Thanks for your solution. It works for me, but this error is still there, i just can't figure out why the `git stash` not clear the staging area.[`git init` just reinit repo]
